# Generated by Django 2.2.13 on 2020-10-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_review_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-id'], 'verbose_name': 'машина', 'verbose_name_plural': 'машины'},
        ),
    ]
